### ISSUE TITLE
Can't load module "client_panorama.dll"

### ISSUE THREAD

**Issue by un4ckn0wl3z** [FiYHer/How-to-create-a-csgo-cheating-program#3]
In Glow and jump tutorial the cheat popup error when run it. I think It's can't find module name "client_panorama.dll" How to fix it?

**Comment by FiYHer** [comment]
> In Glow and jump tutorial the cheat popup error when run it. I think It's can't find module name "client_panorama.dll" How to fix it?

game update, client_panorama.dll to client.dll

**Comment by un4ckn0wl3z** [comment]
> > In Glow and jump tutorial the cheat popup error when run it. I think It's can't find module name "client_panorama.dll" How to fix it?
> 
> game update, client_panorama.dll to client.dll

OK Thanks
